### ISSUE TITLE
Doesn't support docker as provider

### ISSUE THREAD

**Issue by xorb** [terraform-providers/terraform-provider-docker#151] opened 2019-05-24 17:17 UTC
Hi there,

### Terraform Version
Terraform v0.12.0

### Affected Resource(s)
- Docker provider

### Panic Output
Initializing modules...

Initializing provider plugins...
- Checking for available provider plugins...

No available provider "docker" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.

**Comment by mavogel** [comment] 2019-05-26 09:19
Duplicate of #144 and #150

**Closed by mavogel** 2019-05-26 09:19 UTC
