### ISSUE TITLE
Add support for --with-registry-auth flag 

### ISSUE THREAD

**Issue by hatched-DavidMichon** [terraform-providers/terraform-provider-docker#77] opened 2018-07-05 14:17 UTC
When using an AWS ECR registry it turns out that services cannot be pulled without the flag `--with-registry-auth`.

It would be very helpful to have this flag option in `docker_service` and `docker_container` resources.

**Comment by thornycrackers** [comment] 2018-09-04 21:57
:+1:

**Comment by taiidani** [comment] 2019-04-15 15:08
This seems to also be a blocker for Swarms using private Docker Hub registries as well.

**Comment by mavogel** [comment] 2019-04-25 20:34
Yes, I could reproduce this bug. I parsed the registry auths wrongly and test worked because it did not delete the images on the test host before starting the test. Will fix it in #143

**Comment by mavogel** [comment] 2019-05-26 09:44
Closed in #143

**Closed by mavogel** 2019-05-26 09:44 UTC
Labels: bug, enhancement
